<?php declare(strict_types=1);

namespace DeRidderDenHertog\GetCustomers\Type;

final readonly class Customer
{
    public function __construct(
        public ?int $tblKlantenID,
        public ?int $klantnummer,
        public ?string $naam1,
        public ?string $naam2,
        public ?string $naam3,
        public ?string $adres,
        public ?string $pc,
        public ?string $plaats,
        public ?bool $isWerknemer,
        public ?int $factuurBoekenOpWinkel,
        public ?string $debiteurnrBoekhouding,
        public ?string $emailFacturatie,
        public ?int $korting,
        public ?string $btwnummer,
        public ?int $soort,
        public ?int $prijslijn,
        public ?int $pakbonAantalKopieen,
        public ?bool $pakbonZonderPrijzen,
        public ?bool $pakbonStreepHandtekening,
        public ?string $laatsteWijziging,
        public ?int $tblMettlerKortingenKode,
        public ?string $landCodeISO2,
        public ?string $betaalmethode,
        public ?string $telefoonnr,
        public ?string $opmerkingen,
        public ?string $routenr,
        public ?string $frequentieFactureren,
        public ?bool $emballagefactureren,
        public ?string $emailPakbonnen,
        public ?int $tblKlantGrpID,
        public ?string $kaartnr,
        public ?string $geboortedatum,
        public ?string $standaardFactuurTekst,
        public ?string $bezorgAdres,
        public ?string $bezorgPC,
        public ?string $bezorgPlaats,
        public ?bool $incassoTekst,
        public ?string $terattentievanvoordefactuur,
        public ?bool $geenBTWBerekenen,
        public ?bool $magNietMeerOpRekeningKopen,
        public ?bool $bestellingen1,
        public ?bool $bestellingen2,
        public ?bool $bestellingen3,
        public ?bool $bestellingen4,
        public ?bool $bestellingen5,
        public ?bool $bestellingen6,
        public ?bool $bestellingen7,
        public ?bool $klantViaKioskNogNaarKassa,
        public ?bool $klantWilOokUBLBestand,
    ) {}
}
