<?php declare(strict_types=1);

namespace DeRidderDenHertog\GetCustomers\Type\Mapping;

use DeRidderDenHertog\GetCustomers\Type\Customer;

/** @internal */
trait MapsCustomers
{
    /**
     * @param array{
     *     TblKlantenID?: int,
     *     Klantnummer?: int,
     *     Naam1?: string,
     *     Naam2?: string,
     *     Naam3?: string,
     *     Adres?: string,
     *     PC?: string,
     *     Plaats?: string,
     *     IsWerknemer?: bool,
     *     FactuurBoekenOpWinkel?: int,
     *     DebiteurnrBoekhouding?: string,
     *     EmailFacturatie?: string,
     *     Korting?: int,
     *     Btwnummer?: string,
     *     Soort?: int,
     *     Prijslijn?: int,
     *     PakbonAantalKopieen?: int,
     *     PakbonZonderPrijzen?: bool,
     *     PakbonStreepHandtekening?: bool,
     *     LaatsteWijziging?: string,
     *     TblMettlerKortingenKode?: int,
     *     LandCodeISO2?: string,
     *     Betaalmethode?: string,
     *     Telefoonnr?: string,
     *     Opmerkingen?: string,
     *     Routenr?: string,
     *     FrequentieFactureren?: string,
     *     Emballagefactureren?: bool,
     *     EmailPakbonnen?: string,
     *     TblKlantGrpID?: int,
     *     Kaartnr?: string,
     *     Geboortedatum?: string,
     *     StandaardFactuurTekst?: string,
     *     BezorgAdres?: string,
     *     BezorgPC?: string,
     *     BezorgPlaats?: string,
     *     IncassoTekst?: bool,
     *     Terattentievanvoordefactuur?: string,
     *     GeenBTWBerekenen?: bool,
     *     MagNietMeerOpRekeningKopen?: bool,
     *     Bestellingen1?: bool,
     *     Bestellingen2?: bool,
     *     Bestellingen3?: bool,
     *     Bestellingen4?: bool,
     *     Bestellingen5?: bool,
     *     Bestellingen6?: bool,
     *     Bestellingen7?: bool,
     *     KlantViaKioskNogNaarKassa?: bool,
     *     KlantWilOokUBLBestand?: bool,
     * } $customer
     */
    private function toCustomer(array $customer): Customer
    {
        return new Customer(
            tblKlantenID: $customer['TblKlantenID'] ?? null,
            klantnummer: $customer['Klantnummer'] ?? null,
            naam1: $customer['Naam1'] ?? null,
            naam2: $customer['Naam2'] ?? null,
            naam3: $customer['Naam3'] ?? null,
            adres: $customer['Adres'] ?? null,
            pc: $customer['PC'] ?? null,
            plaats: $customer['Plaats'] ?? null,
            isWerknemer: $customer['IsWerknemer'] ?? null,
            factuurBoekenOpWinkel: $customer['FactuurBoekenOpWinkel'] ?? null,
            debiteurnrBoekhouding: $customer['DebiteurnrBoekhouding'] ?? null,
            emailFacturatie: $customer['EmailFacturatie'] ?? null,
            korting: $customer['Korting'] ?? null,
            btwnummer: $customer['Btwnummer'] ?? null,
            soort: $customer['Soort'] ?? null,
            prijslijn: $customer['Prijslijn'] ?? null,
            pakbonAantalKopieen: $customer['PakbonAantalKopieen'] ?? null,
            pakbonZonderPrijzen: $customer['PakbonZonderPrijzen'] ?? null,
            pakbonStreepHandtekening: $customer['PakbonStreepHandtekening'] ?? null,
            laatsteWijziging: $customer['LaatsteWijziging'] ?? null,
            tblMettlerKortingenKode: $customer['TblMettlerKortingenKode'] ?? null,
            landCodeISO2: $customer['LandCodeISO2'] ?? null,
            betaalmethode: $customer['Betaalmethode'] ?? null,
            telefoonnr: $customer['Telefoonnr'] ?? null,
            opmerkingen: $customer['Opmerkingen'] ?? null,
            routenr: $customer['Routenr'] ?? null,
            frequentieFactureren: $customer['FrequentieFactureren'] ?? null,
            emballagefactureren: $customer['Emballagefactureren'] ?? null,
            emailPakbonnen: $customer['EmailPakbonnen'] ?? null,
            tblKlantGrpID: $customer['TblKlantGrpID'] ?? null,
            kaartnr: $customer['Kaartnr'] ?? null,
            geboortedatum: $customer['Geboortedatum'] ?? null,
            standaardFactuurTekst: $customer['StandaardFactuurTekst'] ?? null,
            bezorgAdres: $customer['BezorgAdres'] ?? null,
            bezorgPC: $customer['BezorgPC'] ?? null,
            bezorgPlaats: $customer['BezorgPlaats'] ?? null,
            incassoTekst: $customer['IncassoTekst'] ?? null,
            terattentievanvoordefactuur: $customer['Terattentievanvoordefactuur'] ?? null,
            geenBTWBerekenen: $customer['GeenBTWBerekenen'] ?? null,
            magNietMeerOpRekeningKopen: $customer['MagNietMeerOpRekeningKopen'] ?? null,
            bestellingen1: $customer['Bestellingen1'] ?? null,
            bestellingen2: $customer['Bestellingen2'] ?? null,
            bestellingen3: $customer['Bestellingen3'] ?? null,
            bestellingen4: $customer['Bestellingen4'] ?? null,
            bestellingen5: $customer['Bestellingen5'] ?? null,
            bestellingen6: $customer['Bestellingen6'] ?? null,
            bestellingen7: $customer['Bestellingen7'] ?? null,
            klantViaKioskNogNaarKassa: $customer['KlantViaKioskNogNaarKassa'] ?? null,
            klantWilOokUBLBestand: $customer['KlantWilOokUBLBestand'] ?? null,
        );
    }
}
